# Site settings
author: Blake Marengo
title: 
header-img: img/home-bg.png
email: marengo.blake@gmail.com
copyright_name: Blake Marengo
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  BlakeMarengo

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
